#TODO move this action to https://github.com/micronaut-projects/github-actions
name: Post-build steps for GitHub gradle workflow
description: Perform post-build steps for gradle workflow
inputs:
  java:
    description: java version
    required: true
  gh-token:
    description: github token
    required: true
runs:
  using: "composite"
  steps:
    - name: Optional tear down step
      shell: bash
      env:
        JAVA_VERSION: ${{ inputs.java }}
      run: |
        [ -f ./teardown.sh ] && ./teardown.sh || true
    - name: Publish Test Report
      if: always()
      uses: mikepenz/action-junit-report@v4.2.2
      with:
        check_name: Java CI / Test Report (${{ inputs.java }})
        report_paths: '**/build/test-results/test/TEST-*.xml'
        check_retries: 'true'
    - name: "📜 Upload binary compatibility check results"
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: binary-compatibility-reports
        path: "**/build/reports/binary-compatibility-*.html"
