#TODO move this action to https://github.com/micronaut-projects/github-actions
name: Build steps for GitHub gradle workflow
description: Perform build steps for gradle workflow
inputs:
  java:
    description: java version
    required: true
runs:
  using: "composite"
  steps:
    - name: Build with Gradle
      shell: bash
      run: |
        set -e
        for EXAMPLE in $(ls ./examples); do
          ./gradlew :examples:${EXAMPLE}:test --continue --no-daemon --no-build-cache
        done
      env:
        TESTCONTAINERS_RYUK_DISABLED: 'true'
        PREDICTIVE_TEST_SELECTION: "${{ github.event_name == 'pull_request' && 'true' || 'false' }}"
