plugins {
    id 'io.micronaut.build.internal.kubernetes-examples'
    id 'groovy'
}

micronaut {
    version libs.versions.micronaut.platform.get()
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("micronaut.operator.*")
    }
}

dependencies {
    annotationProcessor(mnValidation.micronaut.validation.processor)
    annotationProcessor(mnSerde.micronaut.serde.processor)
    implementation(mnValidation.micronaut.validation)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(mn.micronaut.management)
    implementation(projects.micronautKubernetesClientOpenapiOperator)
    runtimeOnly(mnLogging.logback.classic)
    runtimeOnly(mnMicrometer.micronaut.micrometer.core)
}

application {
    mainClass.set("micronaut.operator.Application")
}

tasks {
    dockerBuild {
        images = ['micronaut-kubernetes-client-openapi-operator-example']
    }
    dockerBuildNative {
        images = ['micronaut-kubernetes-client-openapi-operator-example']
    }
}
