The Configuration client will read Kubernetes' ``ConfigMap``s and ``Secret``s instances and make them available as ``PropertySource``s
instances in your application.

To get started, you need to declare the following dependency:

dependency:io.micronaut.kubernetes:micronaut-kubernetes-client-openapi-discovery[]

Then, in any bean you can read the configuration values from the `ConfigMap` or `Secret` using `@Value` or
https://docs.micronaut.io/latest/guide/index.html#config[any other way to read configuration values].

Micronaut now supports explicit configuration imports for Kubernetes-backed distributed configuration. Use
`micronaut.config.import` to opt into the exact `ConfigMap` and `Secret` sources your application should read:

[configuration]
----
micronaut:
  config:
    import:
      - kubernetes-configmap:my-config
      - optional:kubernetes-secret:db-credentials?namespace=shared
----

Supported import providers are:

* `kubernetes-configmap:`
* `kubernetes-secret:`

Each import must declare exactly one selector:

* a resource name in the URI path, for example `kubernetes-configmap:my-config`
* or a `labels` query parameter, for example `kubernetes-configmap:?labels=app=my-app,env=prod`

An optional `namespace` query parameter overrides the default Kubernetes namespace resolution:

[configuration]
----
micronaut:
  config:
    import:
      - kubernetes-configmap:my-config?namespace=team-a
      - kubernetes-secret:?labels=app=my-app,env=prod&namespace=shared
----

Authentication-related Kubernetes client options can also be supplied directly on the import connection string when you need the importer to create a dedicated Kubernetes client configuration:

[configuration]
----
micronaut:
  config:
    import:
      - kubernetes-configmap:my-config?namespace=team-a&master-url=https://127.0.0.1:6443&token=my-token&ca-path=file:/etc/certs/ca.crt
----

The same auth options can be provided in map-based syntax as well:

[configuration]
----
micronaut:
  config:
    import:
      - kubernetes-configmap:
          provider: kubernetes-configmap
          path: my-config
          namespace: team-a
          master-url: https://127.0.0.1:6443
          token: my-token
          ca-path: file:/etc/certs/ca.crt
----

Supported auth-related options follow the existing Kubernetes client configuration model, including `master-url`, `token`, `username`, `password`, `service-account-token`, `service-account-token-path`, `client-certificate-path`, `client-key-path`, `client-certificate-data`, `client-key-data`, `ca-path`, `ca-crt-data`, `kube-config-path`, and `insecure-skip-tls-verify`.

Later `micronaut.config.import` entries take precedence over earlier ones when the same property key is present in more than one imported source.

[NOTE]
====
The legacy bootstrap `ConfigurationClient` path remains available for compatibility, but it is deprecated. Prefer explicit `micronaut.config.import` entries for new applications and migrations.
====

## ConfigMaps

Supported formats for ``ConfigMap``s are:

* Java `.properties`.
* YAML.
* JSON.
* Literal values.

The configuration client by default will read all the ``ConfigMap``s for the configured namespace. You can further filter
which config map names are processed by defining `kubernetes.client.config-maps.includes` or
`kubernetes.client.config-maps.excludes`:

[configuration]
----
kubernetes:
  client:
    config-maps:
      includes:
        - my-config-map
        - other-config-map
----

Or:

[configuration]
----
kubernetes:
  client:
    config-maps:
      excludes: not-this-config-map
----

In addition to that, Kubernetes labels can be used to better match the config maps that should be available as property
sources. This can be done by defining the label and value directly:

[configuration]
----
kubernetes:
  client:
    config-maps:
      labels:
        - app: my-app
        - env: prod
----

Or by including every config map that has the same Kubernetes label as the pod the Micronaut application is running in.
This is handy if you use a package manager like https://helm.sh[Helm].
A good example would be `app.kubernetes.io/instance` which is a unique label identifying the instance of an application:

[configuration]
----
kubernetes:
  client:
    config-maps:
      pod-labels:
        - "app.kubernetes.io/instance"
----

Additionally, you can also enable `exception-on-pod-labels-missing` property in case you want an exception to be thrown if at least
one of the labels, specified in `pod-labels` section is not found among the application's pod labels. This can be useful if you want
to prevent loading all config maps available in namespace in case of mistyping or misconfiguration:

[configuration]
----
kubernetes:
  client:
    config-maps:
      exception-on-pod-labels-missing: true
      pod-labels:
        - "app.kubernetes.io/instance"
----

Note that on the resulting config maps, you can still further filter them with includes/excludes properties.

[NOTE]
====
The `includes`, `excludes`, `labels`, `pod-labels`, `exception-on-pod-labels-missing`, `terminate-startup-on-exception`, `paths`, and `use-api` settings documented below apply to the deprecated bootstrap configuration-client mode. They are not part of the new `kubernetes-configmap:` import URI contract.
====

By default if an exception occurs reading config maps on startup, the exception is logged and the service is started.
This can be overridden to terminate the service startup when the service is not able to read config maps because of any
exception by setting the `terminate-startup-on-exception` property to `true` in your application configuration:

[configuration]
----
kubernetes:
  client:
    config-maps:
      terminate-startup-on-exception: true
----


### Reading ``ConfigMap``s from mounted volumes

In the case of ``ConfigMaps``s, reading them from the Kubernetes API requires additional permissions, as stated above.
Therefore, you may want to read them from mounted volumes in the pod.

Given the following ConfigMap:

[source, yaml]
----
apiVersion: v1
kind: ConfigMap
metadata:
  name: mounted-config
data:
  mounted.yml: |-
    foo: bar
----

It can be mounted as a volume in a pod or deployment definition:

[source, yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: micronautapp
    volumeMounts:
    - name: configuration
      mountPath: /etc/configuration
      readOnly: true
  volumes:
  - name: configuration
    configMap:
      name: mounted-config
----

This will make Kubernetes to create file per data entry:

* `/etc/configuration/mounted.yml`

While you could potentially use the `java.io` or `java.nio` APIs to read the contents yourself, this configuration module
can convert them into a ``PropertySource`` so that you can consume the values much more easily. In order to do so, define
the following configuration:

[configuration]
----
kubernetes:
  client:
    config-maps:
      paths:
        - /etc/configuration
----

Each file in the directory will become a property source file. The file format will be automatically deduced based on the file suffix. Supported formats for mounted ``ConfigMap`` files are:

* Java `.properties`
* YAML
* JSON

[NOTE]
====
When `kubernetes.client.config-maps.paths` is defined, the Kubernetes API will not be used to read any other config maps.
If you still want to read the remaining config maps from the API, set the following configuration:

[configuration]
----
kubernetes:
  client:
    config-maps:
      use-api: true
      excludes: mounted-config  # Because it will be read as a mounted volume
      paths:
        - /etc/configuration
----

In this scenario, if there are property keys defined in both type of config maps, the ones coming from mounted volumes will
take precedence over the ones coming from the API.
====

### Watching for changes in ConfigMaps

By default, this configuration module will watch for ``ConfigMap``s added/modified/deleted, and provided that the changes
match with the above filters, they will be propagated to the `Environment` and refresh it.

This means that those changes will be immediately available in your application without a restart.

If you want to disable watching for ConfigMap changes in the deprecated bootstrap mode, set `kubernetes.client.config-maps.watch` to `false`.
This should be done in the `bootstrap.yml` configuration file because the configuration client is initialized during the bootstrap phase, which happens before evaluating the `application.yml` configuration file.

[NOTE]
====
When `kubernetes.client.config-maps.use-api` is set to `false`, watching for the changes won't be started.
For import-based usage, only API-backed imports participate in runtime refresh.
====

### Examples

You can create a Kubernetes `ConfigMap` off an existing file with the following command:

`kubectl create configmap my-config --from-file=my-config.properties`

Or:

`kubectl create configmap my-config --from-file=my-config.yml`

Or:

`kubectl create configmap my-config --from-file=my-config.json`

You can also create a `ConfigMap` from literal values:

`kubectl create configmap my-config --from-literal=special.how=very --from-literal=special.type=charm`

## Secrets

Secrets read from the Kubernetes API will be base64-decoded and made available as `PropertySource` s, so that they can be
also read with `@Value`, `@ConfigurationProperties`, etc.

NOTE: Only `Opaque` secrets will be considered.

By default, secrets access is disabled in the deprecated bootstrap mode. To enable them there, set in `bootstrap.yml`:

[configuration]
----
kubernetes:
  client:
    secrets:
      enabled: true
----

The configuration client, by default, will read all the ``Secret``s for the configured namespace. You can further filter
which secret names are processed by defining `kubernetes.client.secrets.includes` or `kubernetes.client.secrets.excludes`:

[configuration]
----
kubernetes:
  client:
    secrets:
      enabled: true
      includes: this-secret
----

Or:

[configuration]
----
kubernetes:
  client:
    secrets:
      enabled: true
      excludes: not-this-secret
----

Similarly to ``ConfigMap``s, labels can also be used to match the desired secrets:

[configuration]
----
kubernetes:
  client:
    secrets:
      enabled: true
      labels:
        - app: my-app
        - env: prod
----

This also works for pod labels:

[configuration]
----
kubernetes:
  client:
    secrets:
      enabled: true
      pod-labels:
        - "app.kubernetes.io/instance"
----

As well as `exception-on-pod-labels-missing` property:

[configuration]
----
kubernetes:
  client:
    secrets:
      enabled: true
      exception-on-pod-labels-missing: true
      pod-labels:
        - "app.kubernetes.io/instance"
----

Similar to ``ConfigMap``s, if you want to terminate the service startup when the service is not able to read secrets
because of any unexpected exception, you can set `terminate-startup-on-exception` property to `true` in application configuration:

[configuration]
----
kubernetes:
  client:
    secrets:
      terminate-startup-on-exception: true
----

For import-based usage, use `kubernetes-secret:` in `micronaut.config.import` instead of these bootstrap filters. Only `Opaque` secrets are imported, and optional imports should use Micronaut's `optional:` prefix:

[configuration]
----
micronaut:
  config:
    import:
      - optional:kubernetes-secret:db-credentials
      - kubernetes-secret:?labels=app=my-app,role=db
----

`kubernetes-secret:` imports support only `namespace` and `labels` as query options. They do not accept bootstrap-only options such as `includes`, `excludes`, `pod-labels`, `paths`, `use-api`, or `terminate-startup-on-exception`.

### Reading ``Secret``s from mounted volumes

In the case of ``Secret``s, reading them from the Kubernetes API requires additional permissions, as stated above.
Therefore, you may want to read them from mounted volumes in the pod.

Given the following secret:

[source, yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
----

It can be mounted as a volume in a pod or deployment definition:

[source, yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
----

This will make Kubernetes to create 2 files:

* `/etc/foo/username`.
* `/etc/foo/password`.

Their content will be the decoded strings from the original base-64 encoded values.

While you could potentially use the `java.io` or `java.nio` APIs to read the contents yourself, this configuration module
can convert them into a ``PropertySource`` so that you can consume the values much more easily. In order to do so, define
the following configuration:

[configuration]
----
kubernetes:
  client:
    secrets:
      enabled: true
      paths:
        - /etc/foo
----

Each file in the directory will become the property key, and the file contents, the property value.

[NOTE]
====
When `kubernetes.client.secrets.paths` is defined, the Kubernetes API will not be used to read any other secret.
If you still want to read the remaining secrets from the API, set the following configuration:

[configuration]
----
kubernetes:
  client:
    secrets:
      enabled: true
      use-api: true
      excludes: mysecret  # Because it will be read as a mounted volume
      paths:
        - /etc/foo
----

In this scenario, if there are property keys defined in both type of secrets, the ones coming from mounted volumes will
take precedence over the ones coming from the API.
====

### Watching for changes in Secrets

If watch is enabled, this configuration module will watch for ``Secret``s added/modified/deleted, and provided that the
changes match with the above filters, they will be propagated to the `Environment` and refresh it.

This means that those changes will be immediately available in your application without a restart.

If you want to enable watching for Secret changes in the deprecated bootstrap mode, set `kubernetes.client.secrets.watch` to `true`.
This should be done in the `bootstrap.yml` configuration file because the configuration client is initialized during the
bootstrap phase, which happens before evaluating the `application.yml` configuration file.

[NOTE]
====
When `kubernetes.client.secrets.use-api` is set to `false`, watching for the changes won't be started.
For import-based usage, Secret refresh is available only for API-backed imports, and Secret watching remains disabled by default unless explicitly enabled through the existing Kubernetes client watch configuration.
====
