plugins {
    id 'io.micronaut.build.internal.kubernetes-module'
}

dependencies {
    annotationProcessor projects.micronautKubernetesClientProcessor

    api projects.micronautKubernetesClient
    implementation libs.rxjava2

    testImplementation projects.testUtils
}

tasks.withType(me.champeau.gradle.japicmp.JapicmpTask) {
    packageExcludes = ["io.micronaut.kubernetes.client.rxjava2"]
}
