## Micronaut Kubernetes 8.x

=== The official Kubernetes Client upgrade

Micronaut Kubernetes 8.0.0 updates the official Kubernetes Client from v22 to v25.

=== RxJava2 support removal

Micronaut 5 doesn't support RxJava2 so `micronaut-kubernetes-client-rxjava2` module has been removed.

=== Delete object methods of Kubernetes Client OpenAPI client

In Kubernetes Client OpenAPI client, delete methods have been modified to return `DeleteResponse` instead of `V1Status` or type of object that is being deleted.
For example, `deleteNamespace` method of `CoreV1Api` class returned `V1Status`

[source,java]
----
    @Delete("/api/v1/namespaces/{name}")
    @Consumes({"application/json", "application/yaml", "application/vnd.kubernetes.protobuf", "application/cbor"})
    V1Status deleteNamespace(
        @PathVariable("name") @NotNull String name,
        @QueryValue("pretty") @Nullable String pretty,
        @QueryValue("dryRun") @Nullable String dryRun,
        @QueryValue("gracePeriodSeconds") @Nullable Integer gracePeriodSeconds,
        @QueryValue("ignoreStoreReadErrorWithClusterBreakingPotential") @Nullable Boolean ignoreStoreReadErrorWithClusterBreakingPotential,
        @QueryValue("orphanDependents") @Nullable Boolean orphanDependents,
        @QueryValue("propagationPolicy") @Nullable String propagationPolicy,
        @Body @Nullable @Valid V1DeleteOptions body
    );
----

but now returns `DeleteResponse<V1Namespace>`

[source,java]
----
    @Delete("/api/v1/namespaces/{name}")
    @Consumes({"application/json", "application/yaml", "application/vnd.kubernetes.protobuf", "application/cbor"})
    DeleteResponse<V1Namespace> deleteNamespace(
        @PathVariable("name") @NotNull String name,
        @QueryValue("pretty") @Nullable String pretty,
        @QueryValue("dryRun") @Nullable String dryRun,
        @QueryValue("gracePeriodSeconds") @Nullable Integer gracePeriodSeconds,
        @QueryValue("ignoreStoreReadErrorWithClusterBreakingPotential") @Nullable Boolean ignoreStoreReadErrorWithClusterBreakingPotential,
        @QueryValue("orphanDependents") @Nullable Boolean orphanDependents,
        @QueryValue("propagationPolicy") @Nullable String propagationPolicy,
        @Body @Nullable @Valid V1DeleteOptions body
    );
----

The same change has been applied to delete methods from Kubernetes Client OpenAPI Reactive client.

=== Utility methods

The `configMapAsPropertySource` methods of api:kubernetes.util.KubernetesUtils[] class require additional argument `Collection<PropertySourceLoader> propertySourceLoaders` which can be provided using `getPropertySourceLoaders` method from api:context.env.Environment[].

## Micronaut Kubernetes 7.x

Micronaut Kubernetes 7.0.0 updates the official Kubernetes Client from v19 to v22.

Starting from Kubernetes Client v20 the client api was refactored to use the builder pattern when creating client requests which caused breaking changes in all micronaut modules which are using
the official kubernetes client. To support the builder pattern, the reactive client micronaut modules (Reactor, RxJava2 and RxJava3) are recreated and will also cause breaking changes.

## Micronaut Kubernetes 4.x

Micronaut Kubernetes 4.0.0 updates to Kubernetes Client v18 (major). This major upgrade of the Kubernetes Client addresses several security CVEs.

## Micronaut Kubernetes 3.x

This section documents breaking changes between Micronaut Kubernetes 2.x and Micronaut Kubernetes 3.x:

### In-house Kubernetes client removed

The in-house Kubernetes client `io.micronaut.kubernetes.client.v1.*` was deprecated and removed. Instead use the new module `micronaut-kubernetes-client` or the reactive alternatives `micronaut-client-reactor` or `micronaut-client-rxjava2` that extends the client API classes by the reactive support of respective reactive framework.

