The Configuration client will read Kubernetes' ``ConfigMap``s and ``Secret``s instances and make them available as ``PropertySource``s
instances in your application.

Then, in any bean you can read the configuration values from the `ConfigMap` or `Secret` using `@Value` or
https://docs.micronaut.io/latest/guide/index.html#config[any other way to read configuration values].

Configuration parsing happens in the bootstrap phase. Therefore, to enable distributed configuration clients, define the
following in `bootstrap.yml` (or `.properties`, `.json`, etc):

[source,yaml]
----
micronaut:
  config-client:
    enabled: true
----

## ConfigMaps

Supported formats for ``ConfigMap``s are:

* Java `.properties`.
* YAML.
* JSON.
* Literal values.

The configuration client by default will read all the ``ConfigMap``s for the configured namespace. You can further filter
which config map names are processed by defining `kubernetes.client.config-maps.includes` or
`kubernetes.client.config-maps.excludes`:

[source,yaml]
----
kubernetes:
  client:
    config-maps:
      includes:
        - my-config-map
        - other-config-map
----

Or:

[source,yaml]
----
kubernetes:
  client:
    config-maps:
      excludes: not-this-config-map
----

In addition to that, Kubernetes labels can be used to better match the config maps that should be available as property
sources:

[source,yaml]
----
kubernetes:
  client:
    config-maps:
      labels:
        - app: my-app
        - env: prod
----

Note that on the resulting config maps, you can still further filter them with includes/excludes properties.

### Watching for changes in ConfigMaps

By default, this configuration module will watch for ``ConfigMap``s added/modified/deleted, and provided that the changes
match with the above filters, they will be propagated to the `Environment` and refresh it.

This means that those changes will be immediately available in your application without a restart.

If you want to disable watching for ConfigMap changes, set `kubernetes.client.config-maps.watch` to `false`.
This should be done in the `bootstrap.yml` configuration file because the configuration client is initialized during the bootstrap phase, which happens before evaluating the `application.yml` configuration file.

### Examples

You can create a Kubernetes `ConfigMap` off an existing file with the following command:

`kubectl create configmap my-config --from-file=my-config.properties`

Or:

`kubectl create configmap my-config --from-file=my-config.yml`

Or:

`kubectl create configmap my-config --from-file=my-config.json`

You can also create a `ConfigMap` from literal values:

`kubectl create configmap my-config --from-literal=special.how=very --from-literal=special.type=charm`

## Secrets

Secrets read from the Kubernetes API will be base64-decoded and made available as `PropertySource` s, so that they can be
also read with `@Value`, `@ConfigurationProperties`, etc.

NOTE: Only `Opaque` secrets will be considered.

By default, secrets access is diabled. To enable them, set in `bootstrap.yml`:

[source,yaml]
----
kubernetes:
  client:
    secrets:
      enabled: true
----

The configuration client, by default, will read all the ``Secret``s for the configured namespace. You can further filter
which config map names are processed by defining `kubernetes.client.secrets.includes` or `kubernetes.client.secrets.excludes`:

[source,yaml]
----
kubernetes:
  client:
    secrets:
      enabled: true
      includes: this-secret
----

Or:

[source,yaml]
----
kubernetes:
  client:
    secrets:
      enabled: true
      excludes: not-this-secret
----

Similarly to ``ConfigMap``s, labels can also be used to match the desired secrets:

[source,yaml]
----
kubernetes:
  client:
    secrets:
      enabled: true
      labels:
        - app: my-app
        - env: prod
----

## Reading ``ConfigMap``s and ``Secret``s from mounted volumes

In the case of ``Secret``s, reading them from the Kubernetes API requires additional permissions, as stated above.
Therefore, you may want to read them from mounted volumes in the pod.

Given the following secret:

[source, yaml]
----
apiVersion: v1
kind: Secret
metadata:
  name: mysecret
type: Opaque
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
----

It can be mounted as a volume in a pod or deployment definition:

[source, yaml]
----
apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: foo
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: foo
    secret:
      secretName: mysecret
----

This will make Kubernetes to create 2 files:

* `/etc/foo/username`.
* `/etc/foo/password`.

Their content will be the decoded strings from the original base-64 encoded values.

While you could potentially use the `java.io` or `java.nio` APIs to read the contents yourself, this configuration module
can convert them into a ``PropertySource`` so that you can consume the values much more easily. In order to do so, define
the following configuration:

[source,yaml]
----
kubernetes:
  client:
    secrets:
      enabled: true
      paths:
        - /etc/foo
----

Each file in the directory will become the property key, and the file contents, the property value.

[NOTE]
====
When `kubernetes.client.secrets.paths` is defined, the Kubernetes API will not be used to read any other secret.
If you still want to read the remaining secrets from the API, set the following configuration:

[source,yaml]
----
kubernetes:
  client:
    secrets:
      enabled: true
      use-api: true
      excludes: mysecret  # Because it will be read as a mounted volume
      paths:
        - /etc/foo
----

In this scenario, if there are property keys defined in both type of secrets, the ones coming from mounted volumes will
take precedence over the ones coming from the API.
====
