This project eases https://kubernetes.io[Kubernetes] integration with Micronaut.

It adds support for the following features:

* Service Discovery.
* Configuration client for config maps and secrets.

To get started, you need to declare the following dependency:

dependency:io.micronaut.kubernetes:micronaut-kubernetes-discovery-client:{version}[]

Note that this configuration module requires at least Micronaut 1.3.

To use the `BUILD-SNAPSHOT` version of this library, check the
https://docs.micronaut.io/latest/guide/index.html#usingsnapshots[documentation to use snapshots].

The core library for all features can be configured using the following configuration properties:

include::{includedir}configurationProperties/io.micronaut.kubernetes.client.v1.KubernetesConfiguration.adoc[]

## Namespace configuration

When a Micronaut application with this configuration module is running within a Pod in a Kubernetes cluster, it will
infer automatically the namespace it's running from by reading it from the service account secret (which will be
provisioned at `/var/run/secrets/kubernetes.io/serviceaccount/namespace`).

However, the namespace can still be overridden via configuration in `bootstrap.yml`:

[source, yaml]
----
kubernetes:
  client:
    namespace: other-namespace
----