This project eases https://kubernetes.io[Kubernetes] integration with Micronaut by providing the following two different implementation of kubernetes client:

* `micronaut-kubernetes-client` module provides an implementation which integrates with the official https://github.com/kubernetes-client/java[Kubernetes Java SDK] client
* `micronaut-kubernetes-client-openapi` module provides an in-house client implementation which uses Micronaut Netty HTTP Client and generated apis and modules from the Kubernetes Java SDK https://github.com/kubernetes-client/java/blob/master/kubernetes/api/openapi.yaml[OpenApi Spec]

The project adds support for the following features:

* Service Discovery (currently supported only by `micronaut-kubernetes-client`)
* Configuration client for config maps and secrets (currently supported only by `micronaut-kubernetes-client`)
* Kubernetes blocking and non-blocking clients (supported by both `micronaut-kubernetes-client` and `micronaut-kubernetes-client-openapi`)

To use the `BUILD-SNAPSHOT` version of this library, check the
https://docs.micronaut.io/latest/guide/index.html#usingsnapshots[documentation to use snapshots].

## Namespace configuration

When a Micronaut application with this module is running within a Pod in a Kubernetes cluster, it will
infer automatically the namespace it's running from by reading it from the service account secret (which will be
provisioned at `/var/run/secrets/kubernetes.io/serviceaccount/namespace`).

However, the namespace can still be overridden via configuration in `bootstrap.yml`:

[source, yaml]
----
kubernetes:
  client:
    namespace: other-namespace
----
