The `micronaut-kubernetes-informer` module integrates the https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/SharedIndexInformer.html[SharedIndexInformer] that is part of official Kubernetes SDK and simplifies its creation. The Informer is similar to a Watch but an Informer tries to re-list and re-watch to hide failures from the caller and provides a store of all the current resources. Note that the default official implementation https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/SharedInformerFactory.html[SharedInformerFactory] creates shared informers per the Kubernetes resource type. However the module `micronaut-kubernetes-informer` creates namespace scoped informers of the Kubernetes resource type, meaning that the informer is shared per specified namespace and kind.

First you need add a dependency on the `micronaut-kubernetes-informer` module:

dependency:io.micronaut.kubernetes:micronaut-kubernetes-informer:{version}[]

Then create a bean that implements https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/ResourceEventHandler.html[ResourceEventHandler] with the Kubernetes resource type of your choice and add the link:{api}/io/micronaut/kubernetes/client/informer/Informer.html[@Informer] annotation trough which you provide the configuration for the https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/SharedIndexInformer.html[SharedIndexInformer].

The example below illustrates the declaration of the link:{api}/io/micronaut/kubernetes/client/informer/Informer.html[@Informer]  with the https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/ResourceEventHandler.html[ResourceEventHandler] for handling the changes of the Kubernetes `V1ConfigMap` resource.

snippet::io.micronaut.kubernetes.client.informer.ConfigMapInformer[tags="handler", project="kubernetes-informer", source="test"]

<1> The link:{api}/io/micronaut/kubernetes/client/informer/Informer.html[@Informer] annotation defines the Kubernetes resource type, resource list type and resource plural
<2> The https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/ResourceEventHandler.html[ResourceEventHandler] interface declares method handlers for added, updated and deleted resource

To create an Informer for non-namespaced resource, configure the `namespace` argument to `Informer.ALL_NAMESPACE` like presented in the example below:

snippet::io.micronaut.kubernetes.client.informer.ClusterRoleInformer[tags="handler", project="kubernetes-informer", source="test"]

The link:{api}/io/micronaut/kubernetes/informer/Informer.html[@Informer] annotation provides several configuration options:

.Informer optional configuration
|===
|Element |Description

|`namespace` | Namespace of the watched resource. If left empty then namespace is resolved by link:{api}/io/micronaut/kubernetes/client/NamespaceResolver.html[NamespaceResolver]. To watch resources from all namespaces configure this parameter to `Informer.ALL_NAMESPACES`.
|`namespaces` | List of the namespaces of the watcher resource. The https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/SharedIndexInformer.html[SharedIndexInformer] will be created for every namespace and all events will be delivered to the specified `ResourceEventHandler`.
|`namespacesSupplier` | `Supplier` class that provides the list of namespaces to watch. Note that the supplier class needs to be a bean in the application context and it is intended for dynamic evaluation of the namesapces to watch. Finally the `namespace`, `namespaces` and `namespacesSupplier` can be used in combination.
|`labelSelector` | Informer label selector, see https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#label-selectors[Label selectors] for more information. By default there is no label selector.
|`labelSelectorSupplier` | `Supplier` class for the label selector. Note that the supplier class needs to be a bean in the application context. Finally the `labelSelector` and `labelSelectorSupplier` can be used in combination.
|`resyncCheckPeriod` | How often to check the need for resync of resources. If left empty the default resync check period is used.

|===

IMPORTANT: The concept of shared informer means that the https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/SharedIndexInformer.html[SharedIndexInformer] for the respective Kubernetes resource type is registered just once for the given namespace. The next request to register another https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/SharedIndexInformer.html[informer] of the same Kubernetes resource type within the same namespace will result in returning of the previously created informer. In practice if you create two `ResourceEventHandler<V1ConfigMap>` but the `@Informer` annotation will have different optional configuration for `labelSelector` then the `SharedInformerFactory` creates just one `SharedInformer`, meaning the other `@Informer` configuration will be ignored. If the `labelSelector` resp. `labelSelectorSupplier` differs then create one `labelSelector` that matches both cases.

== SharedIndexInformer local cache

The https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/SharedIndexInformer.html[SharedIndexInformer] has internal cache that is eventually consistent with the authoritative state. The local cache starts out empty, and gets populated and updated. For the detailed description of SharedIndexInformer internals visit the reference implementation https://pkg.go.dev/k8s.io/client-go/tools/cache#SharedIndexInformer[pkg.go.dev/k8s.io/client-go#SharedIndexInformer] in Go language.

The cache is exposed by https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/SharedIndexInformer.html[SharedIndexInformer#getIndexer()] method:

snippet::io.micronaut.kubernetes.client.informer.SharedInformerCache[tags="cache", project="kubernetes-informer", source="test"]
