The `micronaut-kubernetes-client` module gives you the ability to use official https://github.com/kubernetes-client/java[Kubernetes Java SDK] apis objects as a regular Micronaut beans.

The complete list of available beans is declared in the link:{sourcedir}/kubernetes-client/src/main/java/io/micronaut/kubernetes/client/Apis.java[Apis#values] annotation value.

First you need add a dependency on the `micronaut-kubernetes-client` module:

dependency:io.micronaut.kubernetes:micronaut-kubernetes-client[]

Then you can simply use Micronaut injection to get configured apis object from package `io.kubernetes.client.openapi.apis` :

[source,java]
----
import io.kubernetes.client.openapi.ApiException;
import io.kubernetes.client.openapi.apis.CoreV1Api;
import io.kubernetes.client.openapi.models.V1PodList;
import jakarta.inject.Singleton;

@Singleton
public class MyService {

    private final CoreV1Api coreV1Api;

    public MyService(CoreV1Api coreV1Api) {
        this.coreV1Api = coreV1Api;
    }

    public void myMethod(String namespace) throws ApiException {
        V1PodList v1PodList = coreV1Api.listNamespacedPod(namespace, null, null, null, null, null, null, null, null, null, false);
    }
}
----

## Authentication
The Kubernetes client source of authentication options is automatically detected by the https://javadoc.io/static/io.kubernetes/client-java/13.0.1/io/kubernetes/client/util/ClientBuilder.html#standard--[ClientBuilder#standard()],
specifically:

Creates a builder which is pre-configured in the following way

* If `$KUBECONFIG` is defined, use that config file.
* If `$HOME/.kube/config` can be found, use that.
* If the in-cluster service account can be found, assume in cluster config.
* Default to `localhost:8080` as a last resort.

Also for specific cases you can update the authentication configuration options by using `kubernetes.client` properties listed below:

|=======
|*Name* |*Description*
|basePath | Kubernetes API base path. Example: `https://localhost:8081`
|caPath | CA file path.
|tokenPath | Token file path.
|kubeConfigPath | Kube config file path.
|verifySsl | Boolean if the api should verify ssl. Default: `true`
|=======

## Reactive Support

In addition to the official Kubernetes Java SDK `Async` clients, this module provides clients that use RxJava or Reactor to allow reactive programming with Micronaut for each Api.

### RxJava 2 Reactive Support

For RxJava 2 add the following dependency:

dependency:io.micronaut.kubernetes:micronaut-kubernetes-client-rxjava2[]

The module contains all official Kubernetes API beans in format `<ApiClassName>RxClient`,
for example the `CoreV1Api` class is injected as `CoreV1ApiRxClient`.

[source,java]
----
import io.kubernetes.client.openapi.ApiException;
import io.kubernetes.client.openapi.models.V1PodList;
import io.micronaut.kubernetes.client.rxjava2.CoreV1ApiRxClient;
import io.reactivex.Single;
import jakarta.inject.Singleton;

@Singleton
public class MyService {

    private final CoreV1ApiRxClient coreV1ApiRxClient;

    public MyService(CoreV1ApiRxClient coreV1ApiRxClient) {
        this.coreV1ApiRxClient = coreV1ApiRxClient;
    }

    public void myMethod(String namespace) {
        Single<V1PodList> v1PodList = coreV1ApiRxClient.listNamespacedPod(namespace, null, null, null, null, null, null, null, null, null);
    }
}
----

### RxJava 3 Reactive Support

For RxJava 3 add the following dependency:

dependency:io.micronaut.kubernetes:micronaut-kubernetes-client-rxjava3[]

The module contains all official Kubernetes API beans in format `<ApiClassName>RxClient`,
for example the `CoreV1Api` class is injected as `CoreV1ApiRxClient`.

[source,java]
----
import io.kubernetes.client.openapi.ApiException;
import io.kubernetes.client.openapi.models.V1PodList;
import io.micronaut.kubernetes.client.rxjava3.CoreV1ApiRxClient;
import io.reactivex.Single;
import jakarta.inject.Singleton;

@Singleton
public class MyService {

    private final CoreV1ApiRxClient coreV1ApiRxClient;

    public MyService(CoreV1ApiRxClient coreV1ApiRxClient) {
        this.coreV1ApiRxClient = coreV1ApiRxClient;
    }

    public void myMethod(String namespace) {
        Single<V1PodList> v1PodList = coreV1ApiRxClient.listNamespacedPod(namespace, null, null, null, null, null, null, null, null, null);
    }
}
----

### Reactor Reactive Support

For Reactor add the following dependency:

dependency:io.micronaut.kubernetes:micronaut-kubernetes-client-reactor[]

The module contains all official Kubernetes API beans in format `<ApiClassName>ReactiveClient`,
for example the `CoreV1Api` class is injected as `CoreV1ApiReactiveClient`.

[source,java]
----
import io.kubernetes.client.openapi.ApiException;
import io.kubernetes.client.openapi.models.V1PodList;
import io.micronaut.kubernetes.client.reactive.CoreV1ApiReactiveClient;
import reactor.core.publisher.Mono;
import jakarta.inject.Singleton;

@Singleton
public class MyService {

    private final CoreV1ApiReactiveClient coreV1ApiReactiveClient;

    public MyService(CoreV1ApiReactiveClient coreV1ApiReactiveClient) {
        this.coreV1ApiReactiveClient = coreV1ApiReactiveClient;
    }

    public void myMethod(String namespace) {
        Mono<V1PodList> v1PodList = coreV1ApiReactiveClient.listNamespacedPod(namespace, null, null, null, null, null, null, null, null, null);
    }
}
----

## Advanced Configuration
For advanced configuration options of `ApiClient` that are not suitable to provide via `application.yml`, you can declare a BeanCreatedEventListener bean that listens for `ApiClient` bean creation, and apply any further customisation to `OkHttpClient` there:

snippet::io.micronaut.kubernetes.client.ApiClientListener[tags="listener", project="kubernetes-client", source="test"]
