The Service Discovery module allows Micronaut HTTP clients to discover Kubernetes services.

To get started, you need to declare the following dependency:

dependency:io.micronaut.kubernetes:micronaut-kubernetes-discovery-client:{version}[]

Then, in any client you can use as Service ID the Kubernetes `Endpoints` name generated by a Kubernetes `Service`.

Consider the following Kubernetes service definition:

[source,yaml]
.`my-service.yml`
----
kind: Service
apiVersion: v1
metadata:
  name: my-service
spec:
  selector:
    app: MyApp
  ports:
  - protocol: TCP
    port: 80
    targetPort: 9376
----

This specification will create a new `Service` object named `my-service`, as well as an `Endpoints` object also named `my-service`.

In your HTTP client, you can use `my-service` as Service ID: `@Client("my-service")`.

## Kubernetes API authentication

Micronaut connects to the Kubernetes API using the `default` service account, which by default only has permissions over
the `kube-system` namespace. This service account needs read permission over the `services` and `endpoints` namespace.
Refer to the https://kubernetes.io/docs/reference/access-authn-authz/rbac/[Kubernetes documentation] for more information
about Role-based access control (RBAC).

One of the options is to create the following `Role` and `RoleBinding`:

[source,yaml]
.`auth.yml`
----
include::{sourcedir}/k8s-auth.yml[]
----

[NOTE]
In Google Cloud's Kubernetes Engine, in order to create the above, you must grant your user the ability to create roles
in Kubernetes by running the following command:

    kubectl create clusterrolebinding cluster-admin-binding --clusterrole cluster-admin --user yourGoogleAccount@gmail.com

## Connecting to services using HTTPS

There are three ways for this library to determine whether a service should be connected to using SSL (the following
examples assume there is a `Deployment` named `secure-deployment`).

### Using `https` as port name

[source,yaml]
.`my-service.yml`
----
include::{sourcedir}/kubernetes.yml[tag=port-name]
----

### Using a port ending in 443

Port numbers like 443, 8443, etc. will match.

[source,yaml]
.`my-service.yml`
----
include::{sourcedir}/kubernetes.yml[tag=port-number]
----

### Using labels

Set a label named `secure` with value `true` to have the client use HTTPS.

[source,yaml]
.`my-service.yml`
----
include::{sourcedir}/kubernetes.yml[tag=labels]
----