plugins {
    id "io.micronaut.build.internal.kubernetes-examples"
    id "groovy"
}

dependencies {
    compileOnly(mn.micronaut.inject.groovy)
    compileOnly(mnValidation.micronaut.validation.processor)
    compileOnly(mnSerde.micronaut.serde.processor)
    implementation(mnValidation.micronaut.validation)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(mn.micronaut.management)
    runtimeOnly(mnLogging.logback.classic)
    testCompileOnly(mn.micronaut.inject.groovy)
    testImplementation(mnTest.micronaut.test.spock)
}
