plugins {
    id "io.micronaut.build.internal.module"
    id "io.micronaut.build.internal.kubernetes-base"
}

// Fix for JavaDoc not finding generated classes
configurations {
    internalJavadocClasspathElements {
        outgoing.artifact(tasks.named("jar"))
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}
