plugins {
    id "io.micronaut.build.internal.module"
    id "io.micronaut.build.internal.kubernetes-base"
    id("org.sonatype.gradle.plugins.scan")
}
String ossIndexUsername = System.getenv("OSS_INDEX_USERNAME") ?: project.properties["ossIndexUsername"]
String ossIndexPassword = System.getenv("OSS_INDEX_PASSWORD") ?: project.properties["ossIndexPassword"]
boolean sonatypePluginConfigured = ossIndexUsername != null && ossIndexPassword != null
if (sonatypePluginConfigured) {
    ossIndexAudit {
        username = ossIndexUsername
        password = ossIndexPassword
        excludeCompileOnly = true
    }
}

// Fix for JavaDoc not finding generated classes
configurations {
    internalJavadocClasspathElements {
        outgoing.artifact(tasks.named("jar"))
    }
}
