plugins {
    id "io.micronaut.build.internal.module"
    id "io.micronaut.build.internal.kubernetes-base"
    id "io.micronaut.build.internal.java-base"
}

// Fix for JavaDoc not finding generated classes
configurations {
    internalJavadocClasspathElements {
        outgoing.artifact(tasks.named("jar"))
    }
}
