#example-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-service
spec:
  selector:
    matchLabels:
      app: example-service
  replicas: 2
  template:
    metadata:
      labels:
        app: example-service
    spec:
      containers:
        - name: example-service
          image: micronaut-kubernetes-example-service
          imagePullPolicy: "Never"
          volumeMounts:
            - name: secrets
              mountPath: "/etc/example-service/secrets"
              readOnly: true
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5004"
          ports:
            - name: http
              containerPort: 8081
            - name: "jvm-debug"
              containerPort: 5004
      volumes:
        - name: secrets
          secret:
            secretName: mounted-secret
            defaultMode: 256
---
apiVersion: v1
kind: Service
metadata:
  name: example-service
  labels:
    foo: bar
spec:
  selector:
    app: example-service
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8081
      targetPort: 8081

#example-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-client
spec:
  selector:
    matchLabels:
      app: example-client
  template:
    metadata:
      labels:
        app: example-client
    spec:
      containers:
        - name: example-client
          image: micronaut-kubernetes-example-client
          imagePullPolicy: "Never"
          env:
            - name: JAVA_TOOL_OPTIONS
              value: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005"
          ports:
            - name: http
              containerPort: 8082
            - name: "jvm-debug"
              containerPort: 5005
---
apiVersion: v1
kind: Service
metadata:
  name: example-client
spec:
  selector:
    app: example-client
  type: LoadBalancer
  ports:
    - protocol: "TCP"
      port: 8082
      targetPort: 8082

#secure-deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-deployment
spec:
  selector:
    matchLabels:
      app: secure-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: secure-deployment
    spec:
      containers:
        - name: secure-deployment
          image: nginx
          ports:
            - containerPort: 80
---
#tag::port-name[]
apiVersion: v1
kind: Service
metadata:
  name: secure-service-port-name
spec:
  selector:
    app: secure-deployment
  type: NodePort
  ports:
    - port: 1234
      protocol: TCP
      name: https
#end::port-name[]
---
#tag::port-number[]
apiVersion: v1
kind: Service
metadata:
  name: secure-service-port-number
spec:
  selector:
    app: secure-deployment
  type: NodePort
  ports:
    - port: 443
      protocol: TCP
#end::port-number[]
---
#tag::labels[]
apiVersion: v1
kind: Service
metadata:
  name: secure-service-labels
  labels:
    secure: "true"
spec:
  selector:
    app: secure-deployment
  type: NodePort
  ports:
    - port: 1234
      protocol: TCP
#end::labels[]
---
apiVersion: v1
kind: Service
metadata:
  name: non-secure-service
spec:
  selector:
    app: secure-deployment
  type: NodePort
  ports:
    - port: 1234
      protocol: TCP