pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
    }
    includeBuild "build-logic"
}

buildscript {
    configurations.classpath {
        resolutionStrategy {
            // micronaut-gradle-plugin 5.0.2 is compiled against native-build-tools 1.1.2 and lacks
            // NativeImageOptions.getLayerCreate() added later; shared.settings 8.0.2 brings 1.1.12
            force 'org.graalvm.buildtools:native-gradle-plugin:1.1.2'
        }
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.1.2'
}

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

rootProject.name = 'kubernetes-parent'

include 'kubernetes-bom'
include 'kubernetes-client'
include 'kubernetes-client-openapi'
include 'kubernetes-client-openapi-common'
include 'kubernetes-client-openapi-discovery'
include 'kubernetes-client-openapi-informer'
include 'kubernetes-client-openapi-operator'
include 'kubernetes-client-openapi-reactor'
include 'kubernetes-client-openapi-watcher'
include 'kubernetes-client-processor'
include 'kubernetes-client-reactor'
include 'kubernetes-client-rxjava3'
include 'kubernetes-discovery-client'
include 'kubernetes-informer'
include 'kubernetes-operator'
include 'test-suite'
include 'test-suite-groovy'
include 'test-suite-kotlin'
include 'test-suite-python'
include 'test-utils'
include 'test-utils-openapi'

include 'examples:example-client'
include 'examples:example-client-openapi'
include 'examples:example-kubernetes-client'
include 'examples:example-kubernetes-client-openapi-informer-java'
include 'examples:example-kubernetes-client-openapi-informer-groovy'
include 'examples:example-kubernetes-client-openapi-informer-kotlin'
include 'examples:example-kubernetes-client-openapi-informer-python'
include 'examples:example-kubernetes-client-openapi-java'
include 'examples:example-kubernetes-client-openapi-groovy'
include 'examples:example-kubernetes-client-openapi-kotlin'
include 'examples:example-kubernetes-client-openapi-python'
include 'examples:example-kubernetes-client-openapi-operator-java'
include 'examples:example-kubernetes-client-openapi-operator-groovy'
include 'examples:example-kubernetes-client-openapi-operator-kotlin'
include 'examples:example-kubernetes-client-openapi-operator-python'
include 'examples:example-kubernetes-client-openapi-reactor-java'
include 'examples:example-kubernetes-client-openapi-reactor-groovy'
include 'examples:example-kubernetes-client-openapi-reactor-kotlin'
include 'examples:example-kubernetes-client-openapi-reactor-python'
include 'examples:example-kubernetes-client-openapi-watcher-java'
include 'examples:example-kubernetes-client-openapi-watcher-groovy'
include 'examples:example-kubernetes-client-openapi-watcher-kotlin'
include 'examples:example-kubernetes-client-openapi-watcher-python'
include 'examples:example-kubernetes-informer'
include 'examples:example-kubernetes-operator'
include 'examples:example-service'
include 'examples:example-service-config-import'
include 'examples:example-service-openapi'
include 'examples:example-service-openapi-config-import'

micronautBuild {
    useStandardizedProjectNames = true
    nonStandardProjectNamePrefixes.add("test-utils")
    nonStandardProjectNamePrefixes.add("examples")

    importMicronautCatalog()
    importMicronautCatalog("micronaut-reactor")
    importMicronautCatalog("micronaut-serde")
    importMicronautCatalog("micronaut-validation")
    importMicronautCatalog("micronaut-openapi")
    importMicronautCatalog("micronaut-micrometer")
}
