import io.micronaut.kubernetes.client.openapi.tasks.DownloadSpec

plugins {
    id 'io.micronaut.build.internal.kubernetes-module'
    id 'io.micronaut.openapi' version libs.versions.micronaut.gradle.plugin
    id 'io.micronaut.kubernetes.client.openapi'
}

micronautBuild {
    binaryCompatibility {
        enabled.set(false)
    }
}

micronaut {
    kubernetesClientOpenApi {
        specVersion = libs.versions.io.kubernetes.client.java.get()
    }
    openapi {
        client("client", tasks.named("downloadOpenApiSpec", DownloadSpec).flatMap(DownloadSpec::getSpecFile)) {
            modelPackageName = "io.micronaut.kubernetes.client.openapi.model"
        }
    }
}

generateClientOpenApiApis.enabled = false

dependencies {
    annotationProcessor(mnValidation.micronaut.validation.processor)
    annotationProcessor(mnSerde.micronaut.serde.processor)
    annotationProcessor(mn.micronaut.inject.java)
    implementation(mnValidation.micronaut.validation)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(mnOpenapi.micronaut.openapi)
    implementation(mn.micronaut.http.client)
}
