import io.micronaut.kubernetes.client.openapi.tasks.DownloadSpec

plugins {
    id 'io.micronaut.build.internal.kubernetes-module'
    id 'io.micronaut.openapi' version libs.versions.micronaut.gradle.plugin
    id 'io.micronaut.kubernetes.client.openapi'
}

kubernetesClientOpenApi {
    specVersion = libs.versions.io.kubernetes.client.java.get()
}

micronaut {
    openapi {
        version = libs.versions.micronaut.openapi.get()
        client("client", tasks.named("downloadOpenApiSpec", DownloadSpec).flatMap(DownloadSpec::getSpecFile)) {
            modelPackageName = "io.micronaut.kubernetes.client.openapi.model"
            dateTimeFormat = "OFFSET_DATETIME"
            additionalProperties.put("dateTimeFormat", "yyyy-MM-dd'T'HH:mm:ss[.SSSSSS]XXX")
            typeMapping.put("int-or-string", "io.micronaut.kubernetes.client.openapi.type.IntOrString")
        }
    }
}

generateClientOpenApiApis.enabled = false

// don't validate javadoc from generated classes
tasks.named("javadoc", Javadoc) {
    options.addBooleanOption("Xdoclint/package:-io.micronaut.kubernetes.client.openapi.model,-io.micronaut.kubernetes.info", true)
}

tasks.withType(me.champeau.gradle.japicmp.JapicmpTask) {
    packageExcludes = ["io.micronaut.kubernetes.client.openapi.model"]
}

tasks.withType(JavaCompile).configureEach {
    options.errorprone.excludedPaths.set(".*/build/generated/.*")
    options.errorprone.option("NullAway:ExcludedClassAnnotations", "jakarta.annotation.Generated")
}

dependencies {
    annotationProcessor(mnValidation.micronaut.validation.processor)
    annotationProcessor(mnSerde.micronaut.serde.processor)
    annotationProcessor(mn.micronaut.inject.java)
    implementation(mnValidation.micronaut.validation)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(mn.micronaut.http.client)
    implementation(mn.snakeyaml)
    compileOnly(platform(mnOpenapi.micronaut.openapi.bom))
}
