plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    implementation("org.yaml:snakeyaml:2.5")
    implementation("org.spockframework:spock-core:2.3-groovy-3.0")
    implementation("org.spockframework:spock-junit4:2.3-groovy-3.0")
}

gradlePlugin {
    plugins {
        kubernetesClientOpenApi {
            id = "io.micronaut.kubernetes.client.openapi"
            implementationClass = "io.micronaut.kubernetes.client.openapi.KubernetesClientOpenApiPlugin"
        }
    }
}

test {
    useJUnitPlatform()
}
