plugins {
    id 'io.micronaut.build.internal.kubernetes-kotlin-examples'
}

micronaut {
    version libs.versions.micronaut.platform.get()
    runtime("netty")
    testRuntime("junit5")
    processing {
        incremental(true)
        annotations("micronaut.client.*")
    }
}

dependencies {
    implementation(projects.micronautKubernetesClientOpenapiWatcher)
}

application {
    mainClass.set("micronaut.client.ApplicationKt")
}
