micronaut:
  application:
    name: micronaut-service
  server:
    port: 8081
    thread-selection: io
    executors:
      io:
        n-threads: 75
        type: fixed
  config-client:
    enabled: true
endpoints:
  env:
    sensitive: false
    enabled: true
  refresh:
    sensitive: false
  health:
    details-visible: ANONYMOUS