micronaut:
  application:
    name: micronaut-service
  server:
    port: 8083
    thread-selection: io
    executors:
      io:
        n-threads: 75
        type: fixed
  config-client:
    enabled: false
  config:
    import:
      - optional:kubernetes://config-map?name=cm-5&watch=true
      - optional:kubernetes://config-map?name=cm-6&watch=true
      - optional:kubernetes://secret?name=sec-5&watch=true
      - optional:kubernetes://config-map?labels=config-set=one&watch=true
      - optional:kubernetes://config-map?labels=config-set=two&watch=false
      - optional:kubernetes://secret?labels=config-set=one&watch=true
      - optional:kubernetes://secret?labels=config-set=two&watch=false
      - optional:file:///etc/example-service-config-import/configmap/mounted.yml
      - optional:file:///etc/example-service-config-import/secrets/mounted-secret.properties
endpoints:
  env:
    sensitive: false
    enabled: true
  refresh:
    sensitive: false
  health:
    details-visible: ANONYMOUS
