import io.micronaut.kubernetes.client.openapi.tasks.DownloadSpec

plugins {
    id 'io.micronaut.build.internal.kubernetes-module'
    id 'io.micronaut.openapi' version libs.versions.micronaut.gradle.plugin
    id 'io.micronaut.kubernetes.client.openapi'
}

micronautBuild {
    binaryCompatibility {
        enabled.set(false)
    }
}

kubernetesClientOpenApi {
    specVersion = libs.versions.io.kubernetes.client.java.get()
}

micronaut {
    openapi {
        client("client", tasks.named("downloadOpenApiSpec", DownloadSpec).flatMap(DownloadSpec::getSpecFile)) {
            apiPackageName = "io.micronaut.kubernetes.client.openapi.api.reactor"
            modelPackageName = "io.micronaut.kubernetes.client.openapi.model"
            apiNameSuffix = "ApiReactor"
            clientId = "kubernetes-client"
            useReactive = true
        }
    }
}

generateClientOpenApiModels.enabled = false

dependencies {
    annotationProcessor(mnValidation.micronaut.validation.processor)
    implementation(mnValidation.micronaut.validation)
    implementation(mnOpenapi.micronaut.openapi)
    api(projects.micronautKubernetesClientOpenapiCommon)
    api(mnReactor.micronaut.reactor)
    testImplementation(libs.testcontainers.k3s)
    testImplementation(mn.micronaut.http.server.netty)
}
