import io.micronaut.kubernetes.client.openapi.tasks.ModifySpec

plugins {
    id 'io.micronaut.build.internal.kubernetes-module'
    id 'io.micronaut.openapi' version libs.versions.micronaut.gradle.plugin
    id 'io.micronaut.kubernetes.client.openapi'
}

kubernetesClientOpenApi {
    specVersion = libs.versions.io.kubernetes.client.java.get()
}

micronaut {
    openapi {
        version = libs.versions.micronaut.openapi.get()
        client("client", tasks.named("modifyOpenApiSpec", ModifySpec).flatMap(ModifySpec::getModifiedSpecFile)) {
            apiPackageName = "io.micronaut.kubernetes.client.openapi.reactor.api"
            modelPackageName = "io.micronaut.kubernetes.client.openapi.model"
            apiNameSuffix = "ApiReactor"
            clientId = "kubernetes"
            useReactive = true
            generateHttpResponseWhereRequired = false
            typeMapping = tasks.named("modifyOpenApiSpec", ModifySpec).flatMap(ModifySpec::getDeleteResponseMappingsFile).map { t->
                return evaluate(t.getAsFile())
            }
            additionalClientTypeAnnotations = [
                    "@io.micronaut.kubernetes.client.openapi.reactor.annotation.KubernetesClientApiReactor",
                    "@io.micronaut.context.annotation.BootstrapContextCompatible"
            ]
        }
    }
}

generateClientOpenApiModels.enabled = false

// don't validate javadoc from generated classes
tasks.named("javadoc", Javadoc) {
    options.addBooleanOption("Xdoclint/package:-io.micronaut.kubernetes.client.openapi.reactor.api,-io.micronaut.kubernetes.info", true)
}

tasks.withType(me.champeau.gradle.japicmp.JapicmpTask) {
    packageExcludes = ["io.micronaut.kubernetes.client.openapi.reactor.api"]
}

dependencies {
    annotationProcessor(mnValidation.micronaut.validation.processor)
    implementation(mnValidation.micronaut.validation)
    api(projects.micronautKubernetesClientOpenapiCommon)
    api(mnReactor.micronaut.reactor)
    compileOnly(platform(mnOpenapi.micronaut.openapi.bom))
    testImplementation(projects.testUtilsOpenapi)
    testImplementation(mn.micronaut.http.server.netty)
}
