[versions]
micronaut-platform = "5.0.3"
micronaut = "5.1.3"
micronaut-gradle-plugin = "5.0.2"

graal-svm = "25.0.3"
javapoet = '1.13.0'
rxjava3 = '3.1.12'
shadow = '9.4.3'
system-lambda = '1.2.1'
io-kubernetes-client-java = '27.0.0'
netty-incubator-codec-http3 = '0.0.30.Final'
testcontainers-k3s = '1.21.4'
bucket4j = '8.10.1'
awaitility = '4.3.0'

micronaut-discovery = "5.0.0"
micronaut-reactor = "4.1.0"
micronaut-serde = "3.1.0"
micronaut-validation = "5.0.0"
micronaut-openapi = "7.0.0"
micronaut-micrometer = "6.0.1"

[libraries]
# Core
micronaut-core = { module = 'io.micronaut:micronaut-core-bom', version.ref = 'micronaut' }
micronaut-platform = { module = 'io.micronaut.platform:micronaut-platform', version.ref = 'micronaut-platform' }

graal-svm = { module = "org.graalvm.nativeimage:svm", version.ref = "graal-svm" }
javapoet = { module = "com.squareup:javapoet", version.ref = "javapoet"  }
rxjava3 = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava3" }
system-lambda = { module = "com.github.stefanbirkner:system-lambda", version.ref = "system-lambda" }

io-kubernetes-client-java = { module = "io.kubernetes:client-java", version.ref = "io-kubernetes-client-java" }
io-kubernetes-client-java-extended = { module = "io.kubernetes:client-java-extended", version.ref = "io-kubernetes-client-java" }
netty-incubator-codec-http3 = { module = "io.netty.incubator:netty-incubator-codec-http3", version.ref = "netty-incubator-codec-http3" }
testcontainers-k3s = { module = "org.testcontainers:k3s", version.ref = "testcontainers-k3s" }
bucket4j = { module = "com.bucket4j:bucket4j-core", version.ref = "bucket4j" }
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

micronaut-reactor = { module = 'io.micronaut.reactor:micronaut-reactor-bom', version.ref = "micronaut-reactor" }
micronaut-serde = { module = 'io.micronaut.serde:micronaut-serde-bom', version.ref = 'micronaut-serde'}
micronaut-validation = { module = 'io.micronaut.validation:micronaut-validation-bom', version.ref = 'micronaut-validation'}
micronaut-openapi = { module = 'io.micronaut.openapi:micronaut-openapi-bom', version.ref = 'micronaut-openapi'}
micronaut-micrometer = { module = "io.micronaut.micrometer:micronaut-micrometer-bom", version.ref = "micronaut-micrometer" }

micronaut-discovery-client = { module = "io.micronaut.discovery:micronaut-discovery-client", version.ref = "micronaut-discovery" }

micronaut-gradle-plugin = { module = "io.micronaut.gradle:micronaut-gradle-plugin", version.ref = "micronaut-gradle-plugin" }
shadow-plugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
