plugins {
    id 'io.micronaut.build.internal.kubernetes-examples'
    id 'groovy'
}

micronaut {
    version libs.versions.micronaut.platform.get()
    runtime("netty")
    testRuntime("spock2")
}

dependencies {
    annotationProcessor(mnValidation.micronaut.validation.processor)
    annotationProcessor(mnSerde.micronaut.serde.processor)
    implementation(mnValidation.micronaut.validation)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(mn.micronaut.management)
    implementation(projects.micronautKubernetesClientOpenapiDiscovery)
    runtimeOnly(mnLogging.logback.classic)
    testImplementation(projects.testUtilsOpenapi)
}

application {
    mainClass.set("micronaut.service.Application")
}

tasks {
    dockerBuild {
        images = ['micronaut-kubernetes-example-service-openapi-config-import']
    }
    dockerBuildNative {
        images = ['micronaut-kubernetes-example-service-openapi-config-import']
    }
}

// tests send requests to a service deployed to a kubernetes cluster
// and since gradle cannot detect changes in the deployed service,
// the cached results are always used so we need to disable the cache
tasks.named('test') {
    outputs.cacheIf { false }
}
