micronaut:
  application:
    name: micronaut-service
  server:
    port: 8085
endpoints:
  env:
    sensitive: false
    enabled: true
  refresh:
    sensitive: false
  health:
    details-visible: ANONYMOUS