plugins {
    id 'io.micronaut.build.internal.kubernetes-examples'
    id("groovy")
}

micronaut {
    version libs.versions.micronaut.platform.get()
    runtime("netty")
    testRuntime("spock2")
    processing {
        incremental(true)
        annotations("micronaut.client.*")
    }
}

dependencies {
    annotationProcessor(mnValidation.micronaut.validation.processor)
    annotationProcessor(mnSerde.micronaut.serde.processor)
    implementation(mnValidation.micronaut.validation)
    implementation(mnSerde.micronaut.serde.jackson)
    implementation(mn.micronaut.http.client)
    implementation(mn.micronaut.management)
    implementation projects.micronautKubernetesDiscoveryClient

    runtimeOnly(mnLogging.logback.classic)

    testImplementation projects.testUtils
    testRuntimeOnly(mnTest.junit.platform.suite)
}

application {
    mainClass.set("micronaut.client.Application")
}

tasks {
    dockerBuild {
        images = ['micronaut-kubernetes-example-client']
    }

    dockerBuildNative {
        images = ['micronaut-kubernetes-example-client']
    }
}

// tests send requests to a service deployed to a kubernetes cluster
// and since gradle cannot detect changes in the deployed service,
// the cached results are always used so we need to disable the cache
tasks.named('test') {
    outputs.cacheIf { false }
}
