plugins {
    id 'io.micronaut.build.internal.kubernetes-module'
}

dependencies {
    annotationProcessor projects.micronautKubernetesClientProcessor
    api projects.micronautKubernetesClient
    api mnReactor.micronaut.reactor

    testImplementation projects.testUtils
}

tasks.withType(me.champeau.gradle.japicmp.JapicmpTask) {
    packageExcludes = ["io.micronaut.kubernetes.client.reactor"]
}
