import io.micronaut.kubernetes.client.openapi.tasks.DownloadSpec

plugins {
    id 'io.micronaut.build.internal.kubernetes-module'
    id 'io.micronaut.openapi' version libs.versions.micronaut.gradle.plugin
    id 'io.micronaut.kubernetes.client.openapi'
}

kubernetesClientOpenApi {
    specVersion = libs.versions.io.kubernetes.client.java.get()
}

micronaut {
    openapi {
        client("client", tasks.named("downloadOpenApiSpec", DownloadSpec).flatMap(DownloadSpec::getSpecFile)) {
            apiPackageName = "io.micronaut.kubernetes.client.openapi.api"
            modelPackageName = "io.micronaut.kubernetes.client.openapi.model"
            clientId = "kubernetes"
            useReactive = false
            generateHttpResponseWhereRequired = false
            additionalClientTypeAnnotations = [
                    "@io.micronaut.context.annotation.BootstrapContextCompatible"
            ]
        }
    }
}

generateClientOpenApiModels.enabled = false

tasks.withType(me.champeau.gradle.japicmp.JapicmpTask) {
    packageExcludes = ["io.micronaut.kubernetes.client.openapi.api"]
}

dependencies {
    annotationProcessor(mnValidation.micronaut.validation.processor)
    implementation(mnValidation.micronaut.validation)
    implementation(mnOpenapi.micronaut.openapi)
    api(projects.micronautKubernetesClientOpenapiCommon)
    testImplementation(libs.testcontainers.k3s)
    testImplementation(mn.micronaut.http.server.netty)
    testImplementation(mn.micronaut.http.client)
    testImplementation(mnReactor.micronaut.reactor)
}
