plugins {
    id 'groovy-gradle-plugin'
}

repositories {
    gradlePluginPortal()
    mavenCentral()
}

dependencies {
    implementation libs.micronaut.gradle.plugin
    implementation libs.shadow.plugin
}

gradlePlugin {
    plugins {
        kubernetesClientOpenApi {
            id = "io.micronaut.kubernetes.client.openapi"
            implementationClass = "io.micronaut.kubernetes.client.openapi.KubernetesClientOpenApiPlugin"
        }
    }
}
