micronaut:
  application:
    name: micronaut-operator
  server:
    thread-selection: io
    executors:
      io:
        n-threads: 75
        type: fixed
endpoints:
  env:
    sensitive: false
  refresh:
    sensitive: false
  health:
    details-visible: ANONYMOUS