#TODO (in template-project): add this file to .rsync-filter once all the repos have this version
#TODO (in template-project): make it like with gradle.yml
#TODO (in a concrete module): remove comments when accepting this change
name: GraalVM CE CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:
  start-runner:
    name: Start self-hosted OracleCloud runners
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-runner.outputs.label }}
    steps:
      - name: Install OCI CLI
        uses: micronaut-projects/github-actions/configure-oracle-cloud-cli@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          oci-user-ocid: ${{ secrets.OCI_USER }}
          oci-region: ${{ secrets.OCI_REGION }}
          oci-tenancy-ocid: ${{ secrets.OCI_TENANCY }}
          oci-private-key: ${{ secrets.OCI_KEY_FILE }}
          oci-private-key-passphrase: ${{ secrets.OCI_PASSPHRASE }}
          oci-private-key-fingerprint: ${{ secrets.OCI_FINGERPRINT }}
      - name: Start runner
        uses: micronaut-projects/github-actions/start-oracle-cloud-runners@master
        id: start-runner
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          oci-compartment-ocid: ${{ secrets.OCI_COMPARTMENT }}
          oci-subnet-ocid: ${{ secrets.OCI_SUBNET }}
          oci-av-domain: ${{ secrets.OCI_AV_DOMAIN }}
          oci-image-ocid: ${{ secrets.OCI_RUNNER_IMAGE }}
          runners-count: '1'
  build:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    needs: start-runner
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['11', '17']
        graalvm: ['latest', 'dev']
        k8s: [ '1.21' ]
    steps:
      # https://github.com/actions/virtual-environments/issues/709
      - name: Free disk space
        run: |
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo apt-get clean
          df -h
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup GraalVM CE
        uses: graalvm/setup-graalvm@v1
        with:
          version: ${{ matrix.graalvm }}
          java-version: ${{ matrix.java }}
          components: 'native-image'
      - name: Setup step
        env:
          K8S_VERSION: ${{ matrix.k8s }}
          JAVA_VERSION: ${{ matrix.java }}
          EXAMPLE_SERVICE_RUNTIME: 'native'
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
        run: |
          [ -f ./setup.sh ] && ./setup.sh || true
      - name: Build with Gradle
        run: |
          if ./gradlew tasks --no-daemon --all | grep -w "testNativeImage"
          then
            ./gradlew check testNativeImage --continue --no-daemon
          else
            ./gradlew check --continue --no-daemon
          fi
        env:
          TESTCONTAINERS_RYUK_DISABLED: true
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
          PREDICTIVE_TEST_SELECTION: "${{ github.event_name == 'pull_request' && 'true' || 'false' }}"
      - name: Optional tear down step
          K8S_VERSION: ${{ matrix.k8s }}
          JAVA_VERSION: ${{ matrix.java }}
        run: |
          [ -f ./teardown.sh ] && ./teardown.sh || true
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3.5.0
        with:
          check_name: GraalVM CE CI / Test Report (Java ${{ matrix.java }})
          report_paths: '**/build/test-results/test/TEST-*.xml'
          check_retries: 'true'
  stop-runner:
    name: Stop self-hosted OracleCloud runners
    needs:
      - start-runner
      - build
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Install OCI CLI
        uses: micronaut-projects/github-actions/configure-oracle-cloud-cli@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          oci-user-ocid: ${{ secrets.OCI_USER }}
          oci-region: ${{ secrets.OCI_REGION }}
          oci-tenancy-ocid: ${{ secrets.OCI_TENANCY }}
          oci-private-key: ${{ secrets.OCI_KEY_FILE }}
          oci-private-key-passphrase: ${{ secrets.OCI_PASSPHRASE }}
          oci-private-key-fingerprint: ${{ secrets.OCI_FINGERPRINT }}
      - name: Stop runners
        uses: micronaut-projects/github-actions/stop-oracle-cloud-runners@master
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          oci-compartment-ocid: ${{ secrets.OCI_COMPARTMENT }}
          oci-runner-label-tag-value: ${{ needs.start-runner.outputs.label }}
