#TODO (in template-project): add this file to .rsync-filter once all the repos have this version
#TODO (in a concrete module): remove comments when accepting this change
name: Java CI
on:
  push:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
  pull_request:
    branches:
      - master
      - '[1-9]+.[0-9]+.x'
jobs:
  start-runner:
    name: Start self-hosted OracleCloud runners
    runs-on: ubuntu-latest
    outputs:
      label: ${{ steps.start-runner.outputs.label }}
    steps:
      - name: Install OCI CLI
        uses: micronaut-projects/github-actions/configure-oracle-cloud-cli@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          oci-user-ocid: ${{ secrets.OCI_USER }}
          oci-region: ${{ secrets.OCI_REGION }}
          oci-tenancy-ocid: ${{ secrets.OCI_TENANCY }}
          oci-private-key: ${{ secrets.OCI_KEY_FILE }}
          oci-private-key-passphrase: ${{ secrets.OCI_PASSPHRASE }}
          oci-private-key-fingerprint: ${{ secrets.OCI_FINGERPRINT }}
      - name: Start runners
        uses: micronaut-projects/github-actions/start-oracle-cloud-runners@master
        id: start-runner
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          oci-compartment-ocid: ${{ secrets.OCI_COMPARTMENT }}
          oci-subnet-ocid: ${{ secrets.OCI_SUBNET }}
          oci-av-domain: ${{ secrets.OCI_AV_DOMAIN }}
          oci-image-ocid: ${{ secrets.OCI_RUNNER_IMAGE }}
          runners-count: '3'
  pre-build:
    strategy:
      matrix:
        java: ['8', '11', '17']
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    uses: micronaut-projects/micronaut-kubernetes/.github/workflows/reusable/gradle-pre-build.yml@master
    with:
      java: ${{ matrix.java }}
    secrets: inherit

  #  ./gradlew check --no-daemon --parallel --continue

  build:
    strategy:
      matrix:
        java: ['8', '11', '17']
    needs: [start-runner, "pre-build (${{ matrix.java }})"]
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    uses: micronaut-projects/micronaut-kubernetes/.github/workflows/reusable/gradle-build.yml@master
    with:
      build_command: |
        #        Add additional variables as needed, for example:
        #        export AWS_ACCESS_KEY_ID="${{ secrets.AWS_ACCESS_KEY_ID }}"
        #        export AWS_SECRET_ACCESS_KEY="${{ secrets.AWS_SECRET_ACCESS_KEY }}"
        #        export AWS_REGION="${{ secrets.AWS_REGION }}"
                       ./gradlew check --no-daemon --parallel --continue
    secrets: inherit

  post-build:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    needs: "build (${{ matrix.java }})"
    uses: micronaut-projects/micronaut-kubernetes/.github/workflows/reusable/gradle-post-build.yml@master
    with:
      java: ${{ matrix.java }}
    secrets: inherit
  stop-runner:
    name: Stop self-hosted OracleCloud runners
    needs:
      - start-runner
      - build
    runs-on: ubuntu-latest
    if: ${{ always() }}
    steps:
      - name: Install OCI CLI
        uses: micronaut-projects/github-actions/configure-oracle-cloud-cli@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          oci-user-ocid: ${{ secrets.OCI_USER }}
          oci-region: ${{ secrets.OCI_REGION }}
          oci-tenancy-ocid: ${{ secrets.OCI_TENANCY }}
          oci-private-key: ${{ secrets.OCI_KEY_FILE }}
          oci-private-key-passphrase: ${{ secrets.OCI_PASSPHRASE }}
          oci-private-key-fingerprint: ${{ secrets.OCI_FINGERPRINT }}
      - name: Stop runners
        uses: micronaut-projects/github-actions/stop-oracle-cloud-runners@master
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          oci-compartment-ocid: ${{ secrets.OCI_COMPARTMENT }}
          oci-runner-label-tag-value: ${{ needs.start-runner.outputs.label }}
