name: Java CI - Common build post setup

on:
  workflow_call:
    inputs:
      java:
        required: true
        type: string

jobs:
  post-build:
    if: github.repository != 'micronaut-projects/micronaut-project-template'
    runs-on: ubuntu-latest
    steps:
      - name: Publish Test Report
        if: always()
        uses: mikepenz/action-junit-report@v3.5.0
        with:
          check_name: Java CI / Test Report (${{ inputs.java }})
          report_paths: '**/build/test-results/test/TEST-*.xml'
          check_retries: 'true'
      - name: "📜 Upload binary compatibility check results"
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: binary-compatibility-reports
          path: "**/build/reports/binary-compatibility-*.html"
      - name: Publish to Sonatype Snapshots
        if: success() && github.event_name == 'push' && inputs.java == '11'
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GRADLE_ENTERPRISE_ACCESS_KEY }}
          GRADLE_ENTERPRISE_CACHE_USERNAME: ${{ secrets.GRADLE_ENTERPRISE_CACHE_USERNAME }}
          GRADLE_ENTERPRISE_CACHE_PASSWORD: ${{ secrets.GRADLE_ENTERPRISE_CACHE_PASSWORD }}
        run: ./gradlew publishToSonatype docs --no-daemon
      - name: Determine docs target repository
        uses: haya14busa/action-cond@v1
        id: docs_target
        with:
          cond: ${{ github.repository == 'micronaut-projects/micronaut-core' }}
          if_true: "micronaut-projects/micronaut-docs"
          if_false: ${{ github.repository }}
      - name: Publish to Github Pages
        if: success() && github.event_name == 'push' && inputs.java == '11'
        uses: micronaut-projects/github-pages-deploy-action@master
        env:
          TARGET_REPOSITORY: ${{ steps.docs_target.outputs.value }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          BRANCH: gh-pages
          FOLDER: build/docs
