apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-deployment
spec:
  selector:
    matchLabels:
      app: secure-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: secure-deployment
    spec:
      containers:
        - name: secure-deployment
          image: nginx
          ports:
            - containerPort: 80
